### PR TITLE
Update .swift-version to 3.1

### PR DESCRIPTION
**Pull request by ianpartridge**

### CODE REVIEW

**Comment by ianpartridge** [comment]
Yes I'll do that too.  Sorry I thought https://github.com/cloudant/swift-cloudant/commit/edba860f7a3fc06a6fbecd02b114e55502f2ffcf had done everything needed.

**Comment by rhyshort** [comment]
Yeah it would have if I noticed the travis version bump when I did it.

**Comment by ianpartridge** [comment]
Done, @rhyshort

**Comment by rhyshort** [comment]
Great, Thanks @ianpartridge

**Pull request merged**
