### PR TITLE
Specify 3.1.1 in .swift-version

### PR DESCRIPTION
**Pull request by ianpartridge**
Swift 3.1.1 is now released.  This is the version which adds support for async usage of `Operation` via `willChangeValue(forKey:)`, as used by this SDK.

Move the `linux-support` branch to this version.

### CODE REVIEW

**Comment by ianpartridge** [comment]
@ricellis here's another small one. Might it be possible for me to get commit access here?

**Comment by ricellis** [comment]
@ianpartridge I'll look into it.

In the meantime I think this needs some additional changes to the `.travis.yml` to get the newer Swift version.

**Comment by ianpartridge** [comment]
Thanks @ricellis - I've updated `.travis.yml`.  The CI failed but it looks like a network issue to me.

**Comment by ricellis** [comment]
The Linux travis build had this issue, which I think will need looking at:
```
/home/travis/build/cloudant/swift-cloudant/Source/SwiftCloudant/HTTP/URLSession.swift:171:37: error: type 'HTTPCookieStorage?' has no member 'shared'

        config.httpCookieStorage = .shared
```

The macOS failure was interestingly the `getChanges` tests, which had been causing problems on Linux, perhaps the failures in those tests are related to Swift 3.1.1 rather than Linux v Mac differences, but I think that is a separate investigation.

**Comment by ianpartridge** [comment]
The Linux failure is known.  `HTTPCookieStorage` is not in Swift 3.1.1 (it'll be in the next release).

Can you try another run to see if the `getChanges` failure is consistent?

**Comment by ianpartridge** [comment]
OK that passed 😄  I think this PR is good to go, then. It won't have affected the macOS build so the intermittent `getChanges` issue must have been there already.

We are still investigating the `getChanges` failure on Linux.

**Pull request merged**
